mybatis:
  type-aliases-package: top.kanetah.planhv2.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planhv2?useSSL=false
    username: root
    password: nicopoiduang
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 1056Mb
server:
#  port: 9713 or 9913, auto configuration on PortConfiguration.kt
  max-http-header-size: 1024
