mybatis:
  type-aliases-package: top.kanetah.planhv2.entity
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planhv2?useSSL=false
    username: root
    password: nicopoiduang
server:
  port: 8080
