mybatis:
  type-aliases-package: top.kanetah.planhv2.entity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planhv2?useSSL=false
    username: root
    password: nicopoiduang
server:
  port: 8888
