mybatis:
  type-aliases-package: top.kanetah.planhv2.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.205.227.77:3306/planhv2?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: nicopoiduang
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 1056Mb
  thymeleaf:
    content-type: text/html
    mode: LEGACYHTML5
    cache: false
  mail:
    host: smtp.qq.com
    username: 2205485120@qq.com
    password: zfygzukhzrsndhjc
    default-encoding: UTF-8
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
server:
#  port: 9713 or 9913, auto configuration by PortConfiguration.kt
  max-http-header-size: 8192
endpoints:
  shutdown:
    enabled: true
management:
  context-path: /super
  security:
    enabled: true
